#!/bin/bash

python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
python train.py --config /tmp/gen_configs/bet_hyper2.json
